/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.disasterredressalmanagementsysterm;

/**
 *
 * @author harsh
 */
public class AssignResponseForce extends javax.swing.JFrame {

    /**
     * Creates new form AssignResponseForce
     */
    public AssignResponseForce() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AssRespLabel = new javax.swing.JLabel();
        StateDisCom = new javax.swing.JLabel();
        StateDisComField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CidAssLabel = new javax.swing.JLabel();
        CompStateAssLabel = new javax.swing.JLabel();
        DisCommAssLabel = new javax.swing.JLabel();
        TFHAssLabel = new javax.swing.JLabel();
        ContactAssLabel = new javax.swing.JLabel();
        TimingsAssLabel = new javax.swing.JLabel();
        AssBtn = new javax.swing.JButton();
        CidAssField = new javax.swing.JTextField();
        CompStateField = new javax.swing.JTextField();
        DisCommAssField = new javax.swing.JTextField();
        ContactAssField = new javax.swing.JTextField();
        TimingsAssField = new javax.swing.JTextField();
        TFHComboBox = new javax.swing.JComboBox<>();
        AssResp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AssRespLabel.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        AssRespLabel.setForeground(new java.awt.Color(255, 255, 255));
        AssRespLabel.setText("ASSIGNING RESPONSE FORCE");
        getContentPane().add(AssRespLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 49, -1, -1));

        StateDisCom.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        StateDisCom.setForeground(new java.awt.Color(255, 255, 255));
        StateDisCom.setText("State");
        getContentPane().add(StateDisCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 150, -1, -1));

        StateDisComField.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        getContentPane().add(StateDisComField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 150, 270, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disaster", "Disaster Committee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1411, 244, -1, -1));

        CidAssLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        CidAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        CidAssLabel.setText("CID");
        getContentPane().add(CidAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 244, -1, -1));

        CompStateAssLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        CompStateAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        CompStateAssLabel.setText("Complaint State");
        getContentPane().add(CompStateAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 319, -1, -1));

        DisCommAssLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        DisCommAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        DisCommAssLabel.setText("Disaster Committee");
        getContentPane().add(DisCommAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 399, -1, -1));

        TFHAssLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        TFHAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        TFHAssLabel.setText("Task Force Head");
        getContentPane().add(TFHAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 480, -1, -1));

        ContactAssLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        ContactAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactAssLabel.setText("Contact");
        getContentPane().add(ContactAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 563, -1, -1));

        TimingsAssLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        TimingsAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        TimingsAssLabel.setText("Timings");
        getContentPane().add(TimingsAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 640, -1, -1));

        AssBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        AssBtn.setText("ASSIGN");
        getContentPane().add(AssBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 800, -1, -1));

        CidAssField.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        getContentPane().add(CidAssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 244, 524, -1));

        CompStateField.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        getContentPane().add(CompStateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 319, 524, -1));

        DisCommAssField.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        getContentPane().add(DisCommAssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 399, 524, -1));

        ContactAssField.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        getContentPane().add(ContactAssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 563, 524, -1));

        TimingsAssField.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        getContentPane().add(TimingsAssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 640, 524, -1));

        TFHComboBox.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        TFHComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(TFHComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 520, -1));

        AssResp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Assign Response Force.png"))); // NOI18N
        AssResp.setText("Label");
        getContentPane().add(AssResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignResponseForce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignResponseForce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignResponseForce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignResponseForce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignResponseForce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssBtn;
    private javax.swing.JLabel AssResp;
    private javax.swing.JLabel AssRespLabel;
    private javax.swing.JTextField CidAssField;
    private javax.swing.JLabel CidAssLabel;
    private javax.swing.JLabel CompStateAssLabel;
    private javax.swing.JTextField CompStateField;
    private javax.swing.JTextField ContactAssField;
    private javax.swing.JLabel ContactAssLabel;
    private javax.swing.JTextField DisCommAssField;
    private javax.swing.JLabel DisCommAssLabel;
    private javax.swing.JLabel StateDisCom;
    private javax.swing.JTextField StateDisComField;
    private javax.swing.JLabel TFHAssLabel;
    private javax.swing.JComboBox<String> TFHComboBox;
    private javax.swing.JTextField TimingsAssField;
    private javax.swing.JLabel TimingsAssLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
