/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.disasterredressalmanagementsysterm;

/**
 *
 * @author harsh
 */
public class CheckStatus extends javax.swing.JFrame {

    /**
     * Creates new form CheckStatus
     */
    public CheckStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComplaintIdLabel = new javax.swing.JLabel();
        ComplaintIdField = new javax.swing.JTextField();
        OrLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        DateFilingField = new javax.swing.JTextField();
        SubmitBtn2 = new javax.swing.JButton();
        SubmitBtn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ActionTableView = new javax.swing.JTable();
        Check = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        setForeground(new java.awt.Color(0, 51, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComplaintIdLabel.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        ComplaintIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        ComplaintIdLabel.setText("Complaint ID");
        getContentPane().add(ComplaintIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 220, -1));

        ComplaintIdField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        ComplaintIdField.setForeground(new java.awt.Color(0, 0, 102));
        ComplaintIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplaintIdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ComplaintIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 500, -1));

        OrLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        OrLabel.setForeground(new java.awt.Color(255, 255, 255));
        OrLabel.setText("(OR)");
        getContentPane().add(OrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 370, -1, -1));

        PhoneLabel.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        PhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhoneLabel.setText("Phone Number");
        getContentPane().add(PhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, 290, -1));

        PhoneField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        PhoneField.setForeground(new java.awt.Color(0, 51, 102));
        PhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 310, 390, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date of filing");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 380, 290, -1));

        DateFilingField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        DateFilingField.setForeground(new java.awt.Color(0, 51, 102));
        DateFilingField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFilingFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DateFilingField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 380, 390, -1));

        SubmitBtn2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        SubmitBtn2.setForeground(new java.awt.Color(0, 0, 102));
        SubmitBtn2.setText("SUBMIT");
        getContentPane().add(SubmitBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 460, -1, -1));

        SubmitBtn1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        SubmitBtn1.setForeground(new java.awt.Color(0, 0, 102));
        SubmitBtn1.setText("SUBMIT");
        getContentPane().add(SubmitBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        ActionTableView.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        ActionTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Place of Occurence", "Task Force Head", "Contact", "Timings", "Disaster Committee"
            }
        ));
        jScrollPane1.setViewportView(ActionTableView);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 1740, -1));

        Check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Check Complaint Status.png"))); // NOI18N
        Check.setText("Label");
        getContentPane().add(Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateFilingFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFilingFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFilingFieldActionPerformed

    private void ComplaintIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplaintIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComplaintIdFieldActionPerformed

    private void PhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ActionTableView;
    private javax.swing.JLabel Check;
    private javax.swing.JTextField ComplaintIdField;
    private javax.swing.JLabel ComplaintIdLabel;
    private javax.swing.JTextField DateFilingField;
    private javax.swing.JLabel OrLabel;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JButton SubmitBtn1;
    private javax.swing.JButton SubmitBtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
