/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.disasterredressalmanagementsysterm;

/**
 *
 * @author harsh
 */
public class MainPage extends javax.swing.JPanel {

    
    /**
     * Creates new form NewJPanel
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        registerComplaint = new javax.swing.JButton();
        disasterProne = new javax.swing.JButton();
        checkStatus = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        AdminLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerComplaint.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        registerComplaint.setForeground(new java.awt.Color(0, 0, 102));
        registerComplaint.setText("Register Complaint");
        add(registerComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 501, 486, -1));

        disasterProne.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        disasterProne.setForeground(new java.awt.Color(0, 0, 102));
        disasterProne.setText("Disaster Prone Zones");
        disasterProne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disasterProneActionPerformed(evt);
            }
        });
        add(disasterProne, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 675, 486, -1));

        checkStatus.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        checkStatus.setForeground(new java.awt.Color(0, 0, 102));
        checkStatus.setText("Check Complaint Status");
        add(checkStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 852, -1, -1));

        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adminlogin.png"))); // NOI18N
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 550, -1, -1));

        AdminLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminLabel.setText("Admin Login");
        add(AdminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 740, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Disaster Risk and Redressal.jpg"))); // NOI18N
        jLabel1.setText("Label");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void disasterProneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disasterProneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disasterProneActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JButton checkStatus;
    private javax.swing.JButton disasterProne;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registerComplaint;
    // End of variables declaration//GEN-END:variables
}
