/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.disasterredressalmanagementsysterm;

/**
 *
 * @author harsh
 */
public class ViewComplaintDetails extends javax.swing.JFrame {

    /**
     * Creates new form ViewAndAssign
     */
    public ViewComplaintDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DateCompLabel = new javax.swing.JLabel();
        DateCompField = new javax.swing.JTextField();
        StateCompLabel = new javax.swing.JLabel();
        StateCompField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ViewCompDetails = new javax.swing.JLabel();
        ViewComp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DateCompLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        DateCompLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateCompLabel.setText("Date");
        getContentPane().add(DateCompLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 209, -1, -1));

        DateCompField.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        DateCompField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateCompFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DateCompField, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 209, 400, -1));

        StateCompLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        StateCompLabel.setForeground(new java.awt.Color(255, 255, 255));
        StateCompLabel.setText("State");
        getContentPane().add(StateCompLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 288, -1, -1));

        StateCompField.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        getContentPane().add(StateCompField, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 283, 400, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "Name", "Phone Number", "Complaint", "Place of incident", "Picture of Proof"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 482, 1719, -1));

        ViewCompDetails.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        ViewCompDetails.setForeground(new java.awt.Color(255, 255, 255));
        ViewCompDetails.setText("VIEW COMPLAINT DETAILS");
        getContentPane().add(ViewCompDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        ViewComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Complaint Details.png"))); // NOI18N
        ViewComp.setText("Label");
        getContentPane().add(ViewComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateCompFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateCompFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateCompFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewComplaintDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewComplaintDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewComplaintDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComplaintDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewComplaintDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateCompField;
    private javax.swing.JLabel DateCompLabel;
    private javax.swing.JTextField StateCompField;
    private javax.swing.JLabel StateCompLabel;
    private javax.swing.JLabel ViewComp;
    private javax.swing.JLabel ViewCompDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
